In [2]:
import pandas as pd
df = pd.read_csv("Chicago_Crimes_2012_to_2017.csv")
df.shape
df.head()
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1456714 entries, 0 to 1456713
Data columns (total 23 columns):
 #   Column                Non-Null Count    Dtype
---  ------                --------------    -----
 0   Unnamed: 0            1456714 non-null  int64
 1   ID                    1456714 non-null  int64
 2   Case Number           1456713 non-null  object
 3   Date                  1456714 non-null  object
 4   Block                 1456714 non-null  object
 5   IUCR                  1456714 non-null  object
 6   Primary Type          1456714 non-null  object
 7   Description           1456714 non-null  object
 8   Location Description  1455056 non-null  object
 9   Arrest                1456714 non-null  bool
 10  Domestic              1456714 non-null  bool
 11  Beat                  1456714 non-null  int64
 12  District              1456713 non-null  float64
 13  Ward                  1456700 non-null  float64
 14  Community Area        1456674 non-null  float64
 15  FBI Code              1456714 non-null  object
 16  X Coordinate          1419631 non-null  float64
 17  Y Coordinate          1419631 non-null  float64
 18  Year                  1456714 non-null  int64
 19  Updated On            1456714 non-null  object
 20  Latitude              1419631 non-null  float64
 21  Longitude             1419631 non-null  float64
 22  Location              1419631 non-null  object
dtypes: bool(2), float64(7), int64(4), object(10)
memory usage: 236.2+ MB

,Unnamed: 0,ID,Beat,District,Ward,Community Area,X Coordinate,Y Coordinate,Year,Latitude,Longitude
count,1.456714e+06,1.456714e+06,1.456714e+06,1.456713e+06,1.456700e+06,1.456674e+06,1.419631e+06,1.419631e+06,1.456714e+06,1.419631e+06,1.419631e+06
mean,3.308606e+06,9.597550e+06,1.150644e+03,1.125920e+01,2.287027e+01,3.745632e+01,1.164398e+06,1.885523e+06,2.013897e+03,4.184147e+01,-8.767224e+01
std,1.235350e+06,8.083505e+05,6.916466e+02,6.904691e+00,1.380589e+01,2.144029e+01,1.850835e+04,3.424775e+04,1.449584e+00,9.430126e-02,6.661726e-02
min,3.000000e+00,2.022400e+04,1.110000e+02,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.012000e+03,3.661945e+01,-9.168657e+01
25%,2.698636e+06,9.002709e+06,6.130000e+02,6.000000e+00,1.000000e+01,2.300000e+01,1.152544e+06,1.858762e+06,2.013000e+03,4.176787e+01,-8.771528e+01
50%,3.063654e+06,9.605776e+06,1.024000e+03,1.000000e+01,2.300000e+01,3.200000e+01,1.166021e+06,1.891502e+06,2.014000e+03,4.185797e+01,-8.766613e+01
75%,3.428849e+06,1.022577e+07,1.711000e+03,1.700000e+01,3.400000e+01,5.600000e+01,1.176363e+06,1.908713e+06,2.015000e+03,4.190529e+01,-8.762813e+01
max,6.253474e+06,1.082788e+07,2.535000e+03,3.100000e+01,5.000000e+01,7.700000e+01,1.205119e+06,1.951573e+06,2.017000e+03,4.202271e+01,-8.752453e+01

In [3]:
df.head()

,Unnamed: 0,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,3,10508693,HZ250496,05/03/2016 11:40:00 PM,013XX S SAWYER AVE,0486,BATTERY,DOMESTIC BATTERY SIMPLE,APARTMENT,True,...,24.0,29.0,08B,1154907.0,1893681.0,2016,05/10/2016 03:56:50 PM,41.864073,-87.706819,"(41.864073157, -87.706818608)"
1,89,10508695,HZ250409,05/03/2016 09:40:00 PM,061XX S DREXEL AVE,0486,BATTERY,DOMESTIC BATTERY SIMPLE,RESIDENCE,False,...,20.0,42.0,08B,1183066.0,1864330.0,2016,05/10/2016 03:56:50 PM,41.782922,-87.604363,"(41.782921527, -87.60436317)"
2,197,10508697,HZ250503,05/03/2016 11:31:00 PM,053XX W CHICAGO AVE,0470,PUBLIC PEACE VIOLATION,RECKLESS CONDUCT,STREET,False,...,37.0,25.0,24,1140789.0,1904819.0,2016,05/10/2016 03:56:50 PM,41.894908,-87.758372,"(41.894908283, -87.758371958)"
3,673,10508698,HZ250424,05/03/2016 10:10:00 PM,049XX W FULTON ST,0460,BATTERY,SIMPLE,SIDEWALK,False,...,28.0,25.0,08B,1143223.0,1901475.0,2016,05/10/2016 03:56:50 PM,41.885687,-87.749516,"(41.885686845, -87.749515983)"
4,911,10508699,HZ250455,05/03/2016 10:00:00 PM,003XX N LOTUS AVE,0820,THEFT,$500 AND UNDER,RESIDENCE,False,...,28.0,25.0,06,1139890.0,1901675.0,2016,05/10/2016 03:56:50 PM,41.886297,-87.761751,"(41.886297242, -87.761750709)"

In [4]:
columns_drop = [
    "Unnamed: 0",
    "ID",
    "Case Number",
    "FBI Code",
    "Updated On",
    "Location"

]
df = df.drop(columns=columns_drop)

In [5]:
df.head()

,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,District,Ward,Community Area,X Coordinate,Y Coordinate,Year,Latitude,Longitude
0,05/03/2016 11:40:00 PM,013XX S SAWYER AVE,0486,BATTERY,DOMESTIC BATTERY SIMPLE,APARTMENT,True,True,1022,10.0,24.0,29.0,1154907.0,1893681.0,2016,41.864073,-87.706819
1,05/03/2016 09:40:00 PM,061XX S DREXEL AVE,0486,BATTERY,DOMESTIC BATTERY SIMPLE,RESIDENCE,False,True,313,3.0,20.0,42.0,1183066.0,1864330.0,2016,41.782922,-87.604363
2,05/03/2016 11:31:00 PM,053XX W CHICAGO AVE,0470,PUBLIC PEACE VIOLATION,RECKLESS CONDUCT,STREET,False,False,1524,15.0,37.0,25.0,1140789.0,1904819.0,2016,41.894908,-87.758372
3,05/03/2016 10:10:00 PM,049XX W FULTON ST,0460,BATTERY,SIMPLE,SIDEWALK,False,False,1532,15.0,28.0,25.0,1143223.0,1901475.0,2016,41.885687,-87.749516
4,05/03/2016 10:00:00 PM,003XX N LOTUS AVE,0820,THEFT,$500 AND UNDER,RESIDENCE,False,True,1523,15.0,28.0,25.0,1139890.0,1901675.0,2016,41.886297,-87.761751

In [6]:
df.isnull().sum().sort_values(ascending=False)

Y Coordinate            37083
Longitude               37083
Latitude                37083
X Coordinate            37083
Location Description     1658
Community Area             40
Ward                       14
District                    1
Date                        0
Beat                        0
Domestic                    0
Arrest                      0
Description                 0
IUCR                        0
Primary Type                0
Block                       0
Year                        0
dtype: int64

In [11]:
df = df.dropna(subset=["Latitude", "Longitude"])
df.head()

,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,District,Ward,Community Area,Year,Latitude,Longitude
0,05/03/2016 11:40:00 PM,013XX S SAWYER AVE,0486,BATTERY,DOMESTIC BATTERY SIMPLE,APARTMENT,True,True,1022,10.0,24.0,29.0,2016,41.864073,-87.706819
1,05/03/2016 09:40:00 PM,061XX S DREXEL AVE,0486,BATTERY,DOMESTIC BATTERY SIMPLE,RESIDENCE,False,True,313,3.0,20.0,42.0,2016,41.782922,-87.604363
2,05/03/2016 11:31:00 PM,053XX W CHICAGO AVE,0470,PUBLIC PEACE VIOLATION,RECKLESS CONDUCT,STREET,False,False,1524,15.0,37.0,25.0,2016,41.894908,-87.758372
3,05/03/2016 10:10:00 PM,049XX W FULTON ST,0460,BATTERY,SIMPLE,SIDEWALK,False,False,1532,15.0,28.0,25.0,2016,41.885687,-87.749516
4,05/03/2016 10:00:00 PM,003XX N LOTUS AVE,0820,THEFT,$500 AND UNDER,RESIDENCE,False,True,1523,15.0,28.0,25.0,2016,41.886297,-87.761751

In [ ]:
df = df.drop(columns=["X Coordinate", "Y Coordinate"])

In [15]:
df["Location Description"].fillna("unknown", inplace=True)
df.head()

C:\Users\mereh\AppData\Local\Temp\ipykernel_18856\1817223606.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Location Description"].fillna("unknown", inplace=True)

,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,District,Ward,Community Area,Year,Latitude,Longitude
0,05/03/2016 11:40:00 PM,013XX S SAWYER AVE,0486,BATTERY,DOMESTIC BATTERY SIMPLE,APARTMENT,True,True,1022,10.0,24.0,29.0,2016,41.864073,-87.706819
1,05/03/2016 09:40:00 PM,061XX S DREXEL AVE,0486,BATTERY,DOMESTIC BATTERY SIMPLE,RESIDENCE,False,True,313,3.0,20.0,42.0,2016,41.782922,-87.604363
2,05/03/2016 11:31:00 PM,053XX W CHICAGO AVE,0470,PUBLIC PEACE VIOLATION,RECKLESS CONDUCT,STREET,False,False,1524,15.0,37.0,25.0,2016,41.894908,-87.758372
3,05/03/2016 10:10:00 PM,049XX W FULTON ST,0460,BATTERY,SIMPLE,SIDEWALK,False,False,1532,15.0,28.0,25.0,2016,41.885687,-87.749516
4,05/03/2016 10:00:00 PM,003XX N LOTUS AVE,0820,THEFT,$500 AND UNDER,RESIDENCE,False,True,1523,15.0,28.0,25.0,2016,41.886297,-87.761751

In [16]:
df["Community Area"].fillna(df["Community Area"].mode()[0], inplace=True)

C:\Users\mereh\AppData\Local\Temp\ipykernel_18856\62115567.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Community Area"].fillna(df["Community Area"].mode()[0], inplace=True)

In [17]:
df["Ward"].fillna(df["Ward"].mode()[0], inplace=True)

C:\Users\mereh\AppData\Local\Temp\ipykernel_18856\1168278067.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Ward"].fillna(df["Ward"].mode()[0], inplace=True)

In [18]:
df["District"].fillna(df["District"].mode()[0], inplace=True)

C:\Users\mereh\AppData\Local\Temp\ipykernel_18856\2244344050.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["District"].fillna(df["District"].mode()[0], inplace=True)

In [19]:
df["District"] = df["District"].astype(int)
df["Ward"] = df["Ward"].astype(int)
df["Community Area"] = df["Community Area"].astype(int)

In [ ]:
df.isnull().sum()

Date                    0
Block                   0
IUCR                    0
Primary Type            0
Description             0
Location Description    0
Arrest                  0
Domestic                0
Beat                    0
District                0
Ward                    0
Community Area          0
Year                    0
Latitude                0
Longitude               0
dtype: int64

In [21]:
df.head()

,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,District,Ward,Community Area,Year,Latitude,Longitude
0,05/03/2016 11:40:00 PM,013XX S SAWYER AVE,0486,BATTERY,DOMESTIC BATTERY SIMPLE,APARTMENT,True,True,1022,10,24,29,2016,41.864073,-87.706819
1,05/03/2016 09:40:00 PM,061XX S DREXEL AVE,0486,BATTERY,DOMESTIC BATTERY SIMPLE,RESIDENCE,False,True,313,3,20,42,2016,41.782922,-87.604363
2,05/03/2016 11:31:00 PM,053XX W CHICAGO AVE,0470,PUBLIC PEACE VIOLATION,RECKLESS CONDUCT,STREET,False,False,1524,15,37,25,2016,41.894908,-87.758372
3,05/03/2016 10:10:00 PM,049XX W FULTON ST,0460,BATTERY,SIMPLE,SIDEWALK,False,False,1532,15,28,25,2016,41.885687,-87.749516
4,05/03/2016 10:00:00 PM,003XX N LOTUS AVE,0820,THEFT,$500 AND UNDER,RESIDENCE,False,True,1523,15,28,25,2016,41.886297,-87.761751

In [22]:
import pandas as pd 
df["Date"] = pd.to_datetime(df["Date"])

C:\Users\mereh\AppData\Local\Temp\ipykernel_18856\1188841744.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["Date"] = pd.to_datetime(df["Date"])

In [23]:
df["Month"] = df["Date"].dt.month

In [24]:
df["Day"] = df["Date"].dt.day

In [25]:
df["Hour"] = df["Date"].dt.hour

In [26]:
df["Dayofweek"] = df["Date"].dt.day_of_week

In [27]:
df.head()

,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,District,Ward,Community Area,Year,Latitude,Longitude,Month,Day,Hour,Dayofweek
0,2016-05-03 23:40:00,013XX S SAWYER AVE,0486,BATTERY,DOMESTIC BATTERY SIMPLE,APARTMENT,True,True,1022,10,24,29,2016,41.864073,-87.706819,5,3,23,1
1,2016-05-03 21:40:00,061XX S DREXEL AVE,0486,BATTERY,DOMESTIC BATTERY SIMPLE,RESIDENCE,False,True,313,3,20,42,2016,41.782922,-87.604363,5,3,21,1
2,2016-05-03 23:31:00,053XX W CHICAGO AVE,0470,PUBLIC PEACE VIOLATION,RECKLESS CONDUCT,STREET,False,False,1524,15,37,25,2016,41.894908,-87.758372,5,3,23,1
3,2016-05-03 22:10:00,049XX W FULTON ST,0460,BATTERY,SIMPLE,SIDEWALK,False,False,1532,15,28,25,2016,41.885687,-87.749516,5,3,22,1
4,2016-05-03 22:00:00,003XX N LOTUS AVE,0820,THEFT,$500 AND UNDER,RESIDENCE,False,True,1523,15,28,25,2016,41.886297,-87.761751,5,3,22,1

In [29]:
df["IsWeekend"] = df["Dayofweek"].apply(lambda x: 1 if x >= 5 else 0)

In [30]:
def Gettimeofday(hour):
    if 5 <= hour < 12:
        return "Morning"
    elif 12 <= hour < 17:
        return "Afternoon"
    elif 17 <= hour < 21:
        return "Evening"
    else:
        return "Night"
df["Timeofday"] = df["Hour"].apply(Gettimeofday)

In [31]:
df.head()

,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,District,...,Community Area,Year,Latitude,Longitude,Month,Day,Hour,Dayofweek,IsWeekend,Timeofday
0,2016-05-03 23:40:00,013XX S SAWYER AVE,0486,BATTERY,DOMESTIC BATTERY SIMPLE,APARTMENT,True,True,1022,10,...,29,2016,41.864073,-87.706819,5,3,23,1,0,Night
1,2016-05-03 21:40:00,061XX S DREXEL AVE,0486,BATTERY,DOMESTIC BATTERY SIMPLE,RESIDENCE,False,True,313,3,...,42,2016,41.782922,-87.604363,5,3,21,1,0,Night
2,2016-05-03 23:31:00,053XX W CHICAGO AVE,0470,PUBLIC PEACE VIOLATION,RECKLESS CONDUCT,STREET,False,False,1524,15,...,25,2016,41.894908,-87.758372,5,3,23,1,0,Night
3,2016-05-03 22:10:00,049XX W FULTON ST,0460,BATTERY,SIMPLE,SIDEWALK,False,False,1532,15,...,25,2016,41.885687,-87.749516,5,3,22,1,0,Night
4,2016-05-03 22:00:00,003XX N LOTUS AVE,0820,THEFT,$500 AND UNDER,RESIDENCE,False,True,1523,15,...,25,2016,41.886297,-87.761751,5,3,22,1,0,Night

In [32]:
df = df.drop(columns=["Date"])

In [33]:
df.head()

,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,District,Ward,Community Area,Year,Latitude,Longitude,Month,Day,Hour,Dayofweek,IsWeekend,Timeofday
0,013XX S SAWYER AVE,0486,BATTERY,DOMESTIC BATTERY SIMPLE,APARTMENT,True,True,1022,10,24,29,2016,41.864073,-87.706819,5,3,23,1,0,Night
1,061XX S DREXEL AVE,0486,BATTERY,DOMESTIC BATTERY SIMPLE,RESIDENCE,False,True,313,3,20,42,2016,41.782922,-87.604363,5,3,21,1,0,Night
2,053XX W CHICAGO AVE,0470,PUBLIC PEACE VIOLATION,RECKLESS CONDUCT,STREET,False,False,1524,15,37,25,2016,41.894908,-87.758372,5,3,23,1,0,Night
3,049XX W FULTON ST,0460,BATTERY,SIMPLE,SIDEWALK,False,False,1532,15,28,25,2016,41.885687,-87.749516,5,3,22,1,0,Night
4,003XX N LOTUS AVE,0820,THEFT,$500 AND UNDER,RESIDENCE,False,True,1523,15,28,25,2016,41.886297,-87.761751,5,3,22,1,0,Night

In [34]:
df.duplicated().sum()

np.int64(4057)

In [ ]:
df[df.duplicated()]

,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,District,Ward,Community Area,Year,Latitude,Longitude,Month,Day,Hour,Dayofweek,IsWeekend,Timeofday
497,071XX S MORGAN ST,1310,CRIMINAL DAMAGE,TO PROPERTY,RESIDENCE,False,False,733,7,17,68,2016,41.764155,-87.649243,5,4,18,2,0,Evening
754,033XX W FILLMORE ST,1812,NARCOTICS,POSS: CANNABIS MORE THAN 30GMS,POLICE FACILITY/VEH PARKING LOT,True,False,1134,11,24,29,2015,41.868181,-87.709271,7,9,6,3,0,Morning
1090,032XX N LECLAIRE AVE,1811,NARCOTICS,POSS: CANNABIS 30GMS OR LESS,"SCHOOL, PUBLIC, BUILDING",True,False,1634,16,30,15,2016,41.939899,-87.754281,5,5,9,3,0,Morning
2194,046XX W MC LEAN AVE,1310,CRIMINAL DAMAGE,TO PROPERTY,RESIDENCE-GARAGE,False,False,2522,25,31,19,2016,41.917878,-87.742752,5,6,17,4,0,Evening
2587,109XX S DOTY AVE E,0860,THEFT,RETAIL THEFT,GROCERY FOOD STORE,True,False,513,5,10,51,2016,41.695908,-87.595823,5,7,16,5,1,Afternoon
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1449377,027XX N MILWAUKEE AVE,1122,DECEPTIVE PRACTICE,COUNTERFEIT CHECK,OTHER,False,False,1412,14,35,22,2016,41.930356,-87.709515,12,28,10,2,0,Morning
1449378,027XX N MILWAUKEE AVE,1122,DECEPTIVE PRACTICE,COUNTERFEIT CHECK,OTHER,False,False,1412,14,35,22,2016,41.930356,-87.709515,12,29,10,3,0,Morning
1449379,027XX N MILWAUKEE AVE,1122,DECEPTIVE PRACTICE,COUNTERFEIT CHECK,OTHER,False,False,1412,14,35,22,2016,41.930356,-87.709515,12,28,10,2,0,Morning
1449381,031XX W GRAND AVE,0620,BURGLARY,UNLAWFUL ENTRY,PARKING LOT/GARAGE(NON.RESID.),False,False,1211,12,27,23,2016,41.897452,-87.704491,12,27,5,1,0,Morning
1451521,080XX S MANISTEE AVE,1790,OFFENSE INVOLVING CHILDREN,CHILD ABDUCTION,RESIDENCE,False,False,422,4,7,46,2016,41.749333,-87.557704,12,25,16,6,1,Afternoon

In [37]:
df = df.drop_duplicates(subset=[
    "Day","Month","Year", "Primary Type", "Latitude", "Longitude"
])

In [38]:
df.duplicated().sum()

np.int64(0)

In [39]:
df.isnull().sum()

Block                   0
IUCR                    0
Primary Type            0
Description             0
Location Description    0
Arrest                  0
Domestic                0
Beat                    0
District                0
Ward                    0
Community Area          0
Year                    0
Latitude                0
Longitude               0
Month                   0
Day                     0
Hour                    0
Dayofweek               0
IsWeekend               0
Timeofday               0
dtype: int64

In [40]:
df = df.drop(columns=["Block"])

In [41]:
df = df.drop(columns=["IUCR"])

In [43]:
df["Year"].unique()

array([2016, 2015, 2013, 2014, 2012, 2017])

In [48]:
df["Primary Type"] = df["Primary Type"].str.lower().str.strip()
df["Description"] = df["Description"].str.lower().str.strip()
df["Location Description"] = df["Location Description"].str.lower().str.strip()
df["Timeofday"] = df["Timeofday"].str.lower().str.strip()

In [49]:
df.head()

,Primary Type,Description,Location Description,Arrest,Domestic,Beat,District,Ward,Community Area,Year,Latitude,Longitude,Month,Day,Hour,Dayofweek,IsWeekend,Timeofday
0,battery,domestic battery simple,apartment,True,True,1022,10,24,29,2016,41.864073,-87.706819,5,3,23,1,0,night
1,battery,domestic battery simple,residence,False,True,313,3,20,42,2016,41.782922,-87.604363,5,3,21,1,0,night
2,public peace violation,reckless conduct,street,False,False,1524,15,37,25,2016,41.894908,-87.758372,5,3,23,1,0,night
3,battery,simple,sidewalk,False,False,1532,15,28,25,2016,41.885687,-87.749516,5,3,22,1,0,night
4,theft,$500 and under,residence,False,True,1523,15,28,25,2016,41.886297,-87.761751,5,3,22,1,0,night

In [50]:
df.to_csv('chicago_crime_cleand.csv', index=False)